### ISSUE TITLE
DS 100 with cs61a + stat134 insteadd of cs61a + stat20

### ISSUE THREAD

**Issue by georgechen1** [DS-100/DS-100.github.io#10]
Hi DS100 Staff,
I would like to enroll in DS 100, but
I have not satisfied all prereqs.

I have not taken data 8, but I have taken cs61a in fa16 with Josh Hug, and stat134 with Henrik/Hank/Fletcher Ibser in fa17. I heard online that cs61b + stat20 satisfy data 8, so I was assuming that stat134 would replace stat20 in this grandfather clause option since it is the higher div version of it.

I have flled out the enrollment appeals option but I have not received a response from Professor Fernandez about it or Denise Yee about it(no idea about Hug yet but I know he is very busy with questions so I felt like it was a better option to pot here--apologies if I should've emailed someone or whatever-the ds 100 website is a bit confusing and hard to navigate for me for where to do based on the faq ).

Please help!
Thanks,
George Chen

**Comment by fperez** [comment]
Hi George,

The waitlist should have been processed by now, it is done periodically. Please let us know if you haven't gotten through by emailing all three of us (Hug, Yee and me).  Filling out the form should be sufficient.
