### ISSUE TITLE
unable to add-- lab is full?

### ISSUE THREAD

**Issue by vsinnarkar** [DS-100/DS-100.github.io#11]
getting the following error when I try to add DS 100 "Class 31426 is full. If a wait list is available, select Add Another Class to return to step 1. Select the class link, select the wait list option and resubmit your request." regardless of which Class ##### is selected for lab

**Comment by simon-mo** [comment]
We don't control CalCentral registration process. sorry about that 😟. please contact stats department.

I would recommend try a lab that's not full; in the past we allow you go to different lab, see #12
