### ISSUE TITLE
Enrolled in DS100 Lab + section + dis but no time for lab + dis yet

### ISSUE THREAD

**Issue by georgechen1** [DS-100/DS-100.github.io#12]
I am successfully enrolled in the lab + section + dis, but unfortunately I do not have
any time stated on calcentral for the discussion or lab. The slot which normally says an interval of time is just blank.

Is this normal/when will the times be given so that we can plan our schedule around the lab + dis's?
Thanks in advance!

**Comment by simon-mo** [comment]
Yes it's normal. 

In the past, this is what we did in the past to "assign" sections:
- At the first few weeks, student would submit their preference for section times. You will fill out your preference for each time slot, like "Strongly Preferred for 4PM-5PM" or "No for 9AM-10AM". 
- We would run a linear program to make sure everyone get their best option available while load-balancing each section. 
- You can still go to other section if the assignment not working out for you. 

My suggestion:
- Pick 1-2 time slot that works for you and plan based on those.
