### ISSUE TITLE
Alternatives to Attendance

### ISSUE THREAD

**Issue by LeviWalsh** [DS-100/DS-100.github.io#14]
If I have another lecture at the same time but want to get attendance points can I attend office hours weekly to get that 5% and have my final weighted 30%? I understand I could have attendance weighted 0% and final weighted 35% but I don't want that option.

**Comment by simon-mo** [comment]
can you post this to Piazza? https://piazza.com/class/jkopvsyuy7g3u0

You can do either private or public note; as the semester approach, we will start using piazza as our main way of communication. 

Thanks!
