### ISSUE TITLE
Does Stat 89A satisfy linear algebra prereq?

### ISSUE THREAD

**Issue by davidwagner** [DS-100/DS-100.github.io#20]
Some places mention Stat 89A as satisfying the linear algebra prerequisite; others don't.  Probably worth being consistent.  Specifically, http://www.ds100.org/sp19faq and https://data.berkeley.edu/education/courses/data-100 doesn't list it.  Maybe update them to list Stat 89A?

**Comment by allenshen5** [comment]
Hi Professor Wagner,

Thank you for noticing this discrepancy; Stat 89A does indeed satisfy the linear algebra prerequisite. I have updated the fall FAQ (http://www.ds100.org/fa19faq) to include Stat 89A, and https://data.berkeley.edu/education/courses/data-100 has been updated as well.
