### ISSUE TITLE
Can I audit the class?

### ISSUE THREAD

**Issue by shankari** [DS-100/DS-100.github.io#21]
I am a final year PhD student, so I don't need the course credit. I don't even need all parts of the course - I could probably help teach the distributed systems part if you wanted :). I just want to better internalize the statistical underpinnings of the data that is relevant to my research, and my advisor suggested auditing this course.

What should I sign up for if I want to just audit the course? Piazza? Internal mailing list?

**Comment by simon-mo** [comment]
Hi 👋 
I believe this class is pretty full right now. [Stats](https://classes.berkeley.edu/content/2019-spring-compsci-c200a-001-lec-001)

But there are webcast and assignments posted on the [website](http://www.ds100.org/sp19/) as well as a class [Piazza](https://piazza.com/class/jq38w3bffphe9)

Lastly there are webcast video from past iteration of this class available at webcast.berkeley.edu
