### ISSUE TITLE
There is no Waitlist option no matter what I do for Data

### ISSUE THREAD

**Issue by yifan-ding** [DS-100/DS-100.github.io#23]
When I try to add myself to the waitlist I can't seem to get on and when I try to click the waitlist option it there is no checkbox where there is usually a "waitlist if full" option. Help pls I know the waitlist is rapidly filling up too

<img width="593" alt="Screen Shot 2019-04-25 at 6 24 39 PM" src="https://user-images.githubusercontent.com/43360483/56777711-c97a6b80-6787-11e9-84e3-ba21f552ff66.png">
<img width="837" alt="Screen Shot 2019-04-25 at 6 25 15 PM" src="https://user-images.githubusercontent.com/43360483/56777718-d13a1000-6787-11e9-9b88-40beb6f67ec3.png">

**Comment by allenshen5** [comment]
Make sure to enroll in the 999 lab and discussion sections. Let me know if you have any further issues.
