### ISSUE TITLE
CS C200C enrollment

### ISSUE THREAD

**Issue by katherinelihanyu** [DS-100/DS-100.github.io#24]
What is the proper way to enroll to the grad version of this class as an EECS fifth year master student? May I have a permission code to enroll? What is my chance of getting in as an EECS 5th year master student?
I couldn’t enroll via CS C200C (the normal sections don’t accept enrollments. I need permission code to get into 999 section)
When I enrolled in STAT C200C, I am waitlisted for all sections even though they have open seats.

**Comment by allenshen5** [comment]
If this has not been resolved yet, feel free to email the instructors.
