### ISSUE TITLE
Question about enrollment in STAT C100

### ISSUE THREAD

**Issue by eglazer** [DS-100/DS-100.github.io#5]
I am already on the waitlist for STAT C100 and tried to submit the appeals form, but I was unable to submit the form because I have not completed one of the prerequisites. How can I submit an appeal asking to enroll in the class if I have the required background knowledge, even if I have not completed the exact prerequisites?

**Comment by eglazer** [comment]
Hi Professor Perez - This was a previous issue which has since been fixed; the old version of the form did not have "other" options.

**Comment by fperez** [comment]
Ah, perfect. Indeed, we did update it to include these after the original release.

Closing this then, thanks for reporting :)
