### ISSUE TITLE
No Waitlist Option for DS100

### ISSUE THREAD

**Issue by elsajy** [DS-100/DS-100.github.io#9]
Hi DS100 Staff,
I'd like to put myself on the waitlist, but CalCentral indicates the class is completely full and the option has disappeared. I have completed all prereqs and just submitted the prereq form to express my interest in the course. I would like to know if you can offer me any guidance for enrollment, e.g. are your hands tied, and should I just be on the lookout for possible waitlist openings?

Thanks,
Elsa

**Comment by fperez** [comment]
Are you still having issues? We've increased enrollment caps so you should have been able to get into the waitlist by now. Please ping us by email if that's not working out so we can look directly at your case.

**Comment by elsajy** [comment]
Hi,

Yes, I'm still having issues. Currently, the class's enrollment status is
closed and the following message is displayed:
COMPSCI     C100
*Error: *Class 27933 is full. If a wait list is available, select Add
Another Class to return to step 1. Select the class link, select the wait
list option and resubmit your request.

The class has been closed since Phase I for me.

Thanks,
Elsa

**Comment by elsajy** [comment]
Hi,

I was wondering whether your staff could take a look at my enrollment case.

I had been keeping an eye on C100 since the beginning of the summer, but
the class has been closed for me since Phase I. I did submit the pre req
form near the beginning of the summer.

Please let me know if there is any chance I will be able to enroll in this
class.

Thanks,
Elsa
